# Generated by Django 3.2 on 2024-04-24 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(2024)], verbose_name='Год'),
        ),
    ]
